{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-survmetrics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SurvMetrics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SurvMetrics/SurvMetrics_{{ version }}.tar.gz
  sha256: d36c937219c90c78c67306753719f65f4de0fd7643cd3bc77af4cf25d4343da8

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-pec
    - r-randomforestsrc
    - r-survival
    - r-survminer
  run:
    - r-base
    - r-mass
    - r-pec
    - r-randomforestsrc
    - r-survival
    - r-survminer

test:
  commands:
    - $R -e "library('SurvMetrics')"           # [not win]
    - "\"%R%\" -e \"library('SurvMetrics')\""  # [win]

about:
  home: https://github.com/skyee1/SurvMetrics
  license: GPL-2.0-or-later
  summary: An implementation of popular evaluation metrics that are commonly used in survival prediction including Concordance Index, Brier Score, Integrated Brier Score, Integrated Square Error, Integrated Absolute Error and Mean Absolute Error. For a detailed information, see (Ishwaran H, Kogalur UB, Blackstone EH and
    Lauer MS (2008) <doi:10.1214/08-AOAS169>) and (Moradian H, Larocque D and Bellavance F (2017) <doi:10.1007/s10985-016-9372-1>) for different evaluation metrics.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
